AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Remind Okan yade

  '
Globals:
  Function:
    Timeout: 10
Resources:
  RemindOkanFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://remind-okan/239355086ad830003b645c15ac7b7e63
      Handler: remind-okan
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /remind-okan
            Method: POST
Outputs:
  RemindOkanAPI:
    Description: API Gateway endpoint URL for Prod environment for First Function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/remind-okan/
  RemindOkanFunction:
    Description: First Lambda Function ARN
    Value:
      Fn::GetAtt:
      - RemindOkanFunction
      - Arn
  RemindOkanFunctionIamRole:
    Description: Implicit IAM Role created for RemindOkan function
    Value:
      Fn::GetAtt:
      - RemindOkanFunctionRole
      - Arn
